---
- name: Trigger and Check GitHub Workflow Status
  hosts: localhost
  gather_facts: false
  vars:
    github_owner: "JDeeptaTech"
    github_repo: "terraform-code-repo"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    api_version: "2022-11-28"
    poll_interval: 10 # Seconds to wait between status checks
    max_attempts: 5 # Maximum number of status checks
  tasks:
    - name: Include Variables
      include_vars:
        dir: vars
        ignore_files: []
        extensions:
          - yaml
          - yml

    - name: Validate action input
      fail:
        msg: "Invalid action input. Please provide a valid action."
      when: action not in ['vm']

    - name: Perform VM Action
      include_tasks: tasks/{{ action }}.yaml

    - name: "Final Workflow Status"
      debug:
        msg: "Final Workflow Status: {{ workflow_status }}, Conclusion: {{ workflow_conclusion }}"
      when: runs_result.json.workflow_runs | length > 0

    - name: "Handle no runs found"
      debug:
        msg: "No workflow runs found."
      when: runs_result.json.workflow_runs | length == 0