- name: "[ GET RUN ] Get Workflow Runs"
  uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/actions/runs?workflow_id={{ workflow_filename }}&branch={{ branch }}&event=workflow_dispatch"
    method: GET
    headers:
      Authorization: "Bearer {{ github_token }}"
      Accept: "application/vnd.github+json"
      X-GitHub-Api-Version: "{{ api_version }}"
  register: runs_result

- name: "[ GET RUN ] Set Run ID"
  set_fact:
    run_id: "{{ runs_result.json.workflow_runs[0].id }}"
  when: runs_result.json.workflow_runs | length > 0